script:
  echo "SUCCESS"
language: python
deploy:
  provider: lambda
  function_name: "travisExpectedPoints"
  region: "us-east-1"
  role: "arn:aws:iam::098833178654:role/service-role/travisExpectedPoints-role-vuwmhpdz"
  runtime: "python3.7"
  handler_name: "lambda_handler"
  module_name: "expectedPointsLambda"
  on:
    branch: travisSetup
# after_deploy:
#   diff -Zq <(curl -s -X GET https://aapdu3qq48.execute-api.us-east-1.amazonaws.com/default/testfunction) correct_function_out.txt
