env:
  - BUILD="expectedPointsModule"
  - BUILD="computeScoreModule"
script:
  - cd $BUILD
  - echo "SUCCESS"
language: python
deploy:
  - provider: lambda
    skip_cleanup: true
    function_name: "travisExpectedPoints"
    region: "us-east-1"
    role: "arn:aws:iam::098833178654:role/service-role/travisExpectedPoints-role-vuwmhpdz"
    runtime: "python3.7"
    handler_name: "lambda_handler"
    module_name: "expectedPointsLambda"
    on:
      branch: travisSetup
      condition: $BUILD = "expectedPointsModule"
  - provider: lambda
    skip_cleanup: true
    function_name: "travisComputeScore"
    region: "us-east-1"
    role: "arn:aws:iam::098833178654:role/service-role/travisComputeScore-role-ym1r3hyc"
    runtime: "python3.7"
    handler_name: "lambda_handler"
    module_name: "computeScoreLambda"
    on:
      branch: travisSetup
      condition: $BUILD = "computeScoreModule"
# after_deploy:
#   diff -Zq <(curl -s -X GET https://aapdu3qq48.execute-api.us-east-1.amazonaws.com/default/testfunction) correct_function_out.txt
