script:
  echo "SUCCESS"
language: python
deploy:
  provider: lambda
  function_name: "testfunction"
  region: "us-east-1"
  role: "arn:aws:iam::858228748133:role/cfbweekly-dev-us-east-1-lambdaRole"
  runtime: "python3.7"
  handler_name: "my_func"
  module_name: "ExpectedPoints/handler"
  on:
    branch: travisSetup
after_deploy:
  - 'diff -q <(curl -s -X GET https://aapdu3qq48.execute-api.us-east-1.amazonaws.com/default/testfunction) <(echo -n '{"username": "thisistheusername", "id": 12}')'
