language: python
python: "3.6"
before_install:
  - pip install awscli
  - pip install aws-sam-cli
script: bash deployCloudFormation.sh
deploy:
  provider: s3
  bucket: "cfbgameoftheweek.com"
  skip_cleanup: true
  local-dir: frontEnd
  acl: public_read
  on:
    branch: travisUpdate