env:
  - BUILD="expectedPointsModule"
  - BUILD="computeScoreModule"
script:
  - cd $BUILD
  - echo "SUCCESS"
  - echo This build was pushed from branch ${TRAVIS_BRANCH}.
language: python
deploy:
  - provider: lambda
    skip_cleanup: true
    function_name: "travisExpectedPoints"
    region: "us-east-1"
    role: "arn:aws:iam::098833178654:role/service-role/travisExpectedPoints-role-vuwmhpdz"
    runtime: "python3.7"
    handler_name: "lambda_handler"
    module_name: "expectedPointsLambda"
    on:
      condition: $BUILD = "expectedPointsModule" && $TRAVIS_BRANCH = travisSetup
  - provider: lambda
    skip_cleanup: true
    function_name: "travisComputeScore"
    region: "us-east-1"
    role: "arn:aws:iam::098833178654:role/service-role/travisComputeScore-role-ym1r3hyc"
    runtime: "python3.7"
    handler_name: "lambda_handler"
    module_name: "computeScoreLambda"
    on:
      condition: $BUILD = "computeScoreModule" && $TRAVIS_BRANCH = travisSetup
  # - provider: lambda
  #   skip_cleanup: true
  #   function_name: "expectedPoints"
  #   region: "us-east-1"
  #   role: "arn:aws:iam::098833178654:role/ExpectedPointsRole"
  #   runtime: "python3.7"
  #   handler_name: "lambda_handler"
  #   module_name: "computeScoreLambda"
  #   on:
  #     condition: $BUILD = "computeScoreModule" && $TRAVIS_BRANCH != travisSetup && $TRAVIS_BRANCH != master
  # - provider: lambda
  #   skip_cleanup: true
  #   function_name: "computeScore"
  #   region: "us-east-1"
  #   role: "arn:aws:iam::098833178654:role/CalculateScoreRole"
  #   runtime: "python3.7"
  #   handler_name: "lambda_handler"
  #   module_name: "computeScoreLambda"
  #   on:
  #     condition: $BUILD = "computeScoreModule" && $TRAVIS_BRANCH != travisSetup && $TRAVIS_BRANCH != master
