language: python
python: "3.6"
before_install:
  - pip install awscli
  - pip install aws-sam-cli
script: . deployCloudFormation.sh
deploy:
  - provider: s3
    bucket: ${WEB_BUCKET_NAME}
    skip_cleanup: true
    local-dir: frontEnd
    on:
        branch: master
after_deploy: echo https://s3.amazonaws.com/${WEB_BUCKET_NAME}/index.html
