script:
  echo "SUCCESS"
language: python
deploy:
  provider: lambda
  function_name: "testfunction"
  region: "us-east-1"
  role: "arn:aws:iam::858228748133:role/cfbweekly-dev-us-east-1-lambdaRole"
  runtime: "python2.7"
  handler_name: "my_func"
  module_name: "ExpectedPoints/handler"
  on:
    branch: travisSetup
