before_install:
  - pip install awscli
  - pip install aws-sam-cli
script:
  - echo "SUCCESS"
  - echo This build was pushed from branch ${TRAVIS_BRANCH}.
language: python
deploy:
  - provider: script
    script: bash upload.sh
    on:
      branch: travisUpdate